name: Workflow evento
on:
  workflow_dispatch:
    inputs:
        valor_numerico:
            type: number
            default: 20
        valor_string:
            type: string
            default: "Valor XPTO"
        valor_boolean:
            type: boolean
            default: true
jobs:
  teste:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Função Contains
        run: echo ${{ contains(inputs.valor_string, github.actor) }}
      - name: Função Format
        run: "echo ${{ format('Formato String: {0} - Formato Number: {1} - Formato boolean: {2}', inputs.valor_string, inputs.valor_numerico, inputs.valor_boolean) }}"
      - name: Função json
        run: echo ${{ toJson(github) }}
        